export const WORKER_LIST = {
  GET_WORKER_LIST: "GET_WORKER_LIST",

  CHANGE_PAGE: "CHANGE_PAGE",

  GET_LIST_LENGTH: "GET_LIST_LENGTH",

  CHANGE_COUNT_ON_PAGE: "CHANGE_COUNT_ON_PAGE",

  DELETE_WORKER: "DELETE_WORKER",

  CREATE_WORKER: "CREATE_WORKER",

  SORT_WORKER: "SORT_WORKER",

  EDIT_WORKER: "EDIT_WORKER",

  FILTER_WORKER: "FILTER_WORKER",

  FILTER_WORKER_NOT_FOP: "FILTER_WORKER_NOT_FOP",
};
